baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The 2 Hour Workday'
theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "dracula"
tabWidth = 4

[params]

colortheme = "white" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = false # default
logo = "/images/logo.png"

# Home page settings
description = "Perspectives on how much one should _work_ are all over the board: Most work nine-to-five, some suggests the possibility of a [four hour work week](https://www.amazon.com/4-hour-Paperback-author-Timothy-Ferriss/dp/B00BDXF6KC/ref=sr_1_2?crid=77NYW0GY2QVB&keywords=four+hour+work+week&qid=1638757969&sprefix=four+hour+w%2Caps%2C168&sr=8-2), increasingly many are gig-workers, some are work-a-holics, and yet others [feel like four or five hours is enough to earn your stay on the planet for one more day](https://opinionator.blogs.nytimes.com/2012/06/30/the-busy-trap/). This site is a my take on _work_, which I define as trading trading time now for money now. It feels to me that we live in a world of financial and opportunity abundance. And my guess is that if we labor with spirit, an open mind, and a cup of tea, then two hours of work per day should be more than enough a avoid ever getting a real job!"
mainSection = "posts" # your main section
showAllPostsOnHomePage = false # default
postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = true # show tags overview by default.
showProjectsList = true # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/gohugoio" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true # default
showReadTime = true # default

[params.comments]
enabled = false # default
engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
[params.comments.utterances]
repo = "<github_username>/<github_reponame>"
label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
theme = "github-light"
[params.comments.cactuscomments]
siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
#serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
#serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
#[[params.social]]
#name = "github"
#link = "https://github.com/gohugoio"
#[[params.social]]
#name = "linkedin"
#link = "https://www.linkedin.com/company/github/"
#[[params.social]]
#name = "email"
#link = "example@example.com"  # no need for "mailto:" in the head
